# -*- coding: utf-8 -*-
"""File_handling_and_exception_handling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oG9iv8UngKd4km89_vBX1xVpq0eBg4ie
"""

def process_file():
    # Ask the user for the input filename
    filename = input("📂 Enter the name of the file to process: ")

    try:
        # Try to open and read the file
        with open(filename, "r") as file:
            content = file.read()

        # Process the content
        word_count = len(content.split())
        uppercase_content = content.upper()

        # Write the modified content to a new file
        with open("output.txt", "w") as output_file:
            output_file.write("MODIFIED CONTENT:\n")
            output_file.write(uppercase_content + "\n")
            output_file.write(f"WORD COUNT: {word_count}\n")

        print("🎉 Success! 'output.txt' has been created with the processed content.")

    except FileNotFoundError:
        print(f"❌ Error: The file '{filename}' was not found.")
    except IOError:
        print(f"❌ Error: Unable to read or write to the file '{filename}'.")
    except Exception as e:
        print(f"❌ Unexpected error: {e}")

# Run the function
process_file()